[theme]
base = "light"
primaryColor = "#5980A6"
backgroundColor = "#F2F2F3"
secondaryBackgroundColor = "#E9E9EA"
textColor = "#1D1F20"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
headless = true
